name: Test

on:
  workflow_dispatch:
    inputs:
      tag:
        description: >
          Select a tag to run tests. Available tags: 
          regress, 
          smoke, 
          main-page, 
          careers-page
        required: false
        default: 'regress'
        type: string
      browser_version:
        description: >
          Select a browser version to run tests. 
          Example: 133.0, 132.0, etc.
        required: false
        default: '133.0'
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - uses: Xotabu4/selenoid-github-action@v2
      - name: Run tests
        run: ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub -PincludeTags=${{ github.event.inputs.tag }} -Dbrowser_version=${{ github.event.inputs.browser_version }}
      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: Generate allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          gh_pages: gh-pages
          allure_results: build/allure-results
          allure_report: allure-report
          allure_history: allure-history
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
